package in.sp.main.Entities;

public enum DoctorVerificationActionType {
    SUBMITTED,
    RESUBMITTED,
    APPROVED,
    REJECTED,
    CHANGES_REQUESTED,
    REVERIFICATION_SUBMITTED,
    REVERIFICATION_APPROVED,
    REVERIFICATION_REJECTED,
    REVERIFICATION_CHANGES_REQUESTED
}
