package in.sp.main.Entities;

public enum OtpPurpose {
    USER_REGISTER,
    DOCTOR_REGISTER,
    CENTRE_REGISTER,
    FITNESS_REGISTER,
    SALON_REGISTER,
    STYLIST_REGISTER,
    MARKETPLACE_REGISTER,
    SELLER_REGISTER,
    EVENT_HOST_REGISTER,
    ENTREPRENEUR_REGISTER,
    INVESTOR_REGISTER,
    JOB_WORKER_REGISTER,
    DELIVERY_REGISTER,
    CREATOR_REGISTER,
    FINANCIAL_REGISTER
}
