name: fight_d_fear
description: Women safety MVP — SOS, contacts, live location.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  geolocator: ^13.0.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  video_player: ^2.9.2
  razorpay_flutter: ^1.4.0
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fightdfear-logo.jpg
    - assets/images/fighthero.jpeg
