ALTER TABLE `user`
    ADD COLUMN IF NOT EXISTS creator_designation VARCHAR(128),
    ADD COLUMN IF NOT EXISTS creator_whatsapp VARCHAR(32),
    ADD COLUMN IF NOT EXISTS creator_address TEXT,
    ADD COLUMN IF NOT EXISTS creator_state VARCHAR(64),
    ADD COLUMN IF NOT EXISTS creator_pincode VARCHAR(16),
    ADD COLUMN IF NOT EXISTS creator_latitude DOUBLE,
    ADD COLUMN IF NOT EXISTS creator_longitude DOUBLE,
    ADD COLUMN IF NOT EXISTS creator_audience TEXT,
    ADD COLUMN IF NOT EXISTS creator_door_service BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS creator_facilities TEXT,
    ADD COLUMN IF NOT EXISTS creator_open_days VARCHAR(255),
    ADD COLUMN IF NOT EXISTS creator_open_time TIME,
    ADD COLUMN IF NOT EXISTS creator_close_time TIME,
    ADD COLUMN IF NOT EXISTS creator_break_start TIME,
    ADD COLUMN IF NOT EXISTS creator_break_end TIME,
    ADD COLUMN IF NOT EXISTS creator_blocked_dates TEXT,
    ADD COLUMN IF NOT EXISTS creator_credential_number VARCHAR(128),
    ADD COLUMN IF NOT EXISTS creator_session_mode VARCHAR(64),
    ADD COLUMN IF NOT EXISTS creator_duration_minutes INT,
    ADD COLUMN IF NOT EXISTS creator_buffer_minutes INT,
    ADD COLUMN IF NOT EXISTS creator_typical_price DOUBLE,
    ADD COLUMN IF NOT EXISTS creator_upi_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS creator_bank_details TEXT,
    ADD COLUMN IF NOT EXISTS creator_payout_balance DOUBLE DEFAULT 0,
    ADD COLUMN IF NOT EXISTS creator_payout_requested_at DATETIME,
    ADD COLUMN IF NOT EXISTS creator_gallery_photos TEXT,
    ADD COLUMN IF NOT EXISTS creator_rating DOUBLE DEFAULT 0,
    ADD COLUMN IF NOT EXISTS creator_review_count INT DEFAULT 0;

CREATE TABLE IF NOT EXISTS creator_reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    creator_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT,
    review_text VARCHAR(2000),
    created_at DATETIME,
    CONSTRAINT fk_creator_review_creator FOREIGN KEY (creator_id) REFERENCES `user`(id),
    CONSTRAINT fk_creator_review_user FOREIGN KEY (user_id) REFERENCES `user`(id)
);
